version: "3.8"

services:

  fit-service:
    build:
      context: ./fit-service
      dockerfile: Dockerfile.dev
    container_name: fit-service
    ports:
      - "${FIT_SERVICE_PORT:-8080}:8080"
    env_file:
      - .env
      - ./fit-service/.env
    environment:
      - FIT_SERVICE_HOST=http://fit-service:${FIT_SERVICE_PORT:-8080}
      - STATISTIC_SERVICE_HOST=http://statistic-service:${STATISTIC_SERVICE_PORT:-8081}
      - USER_SERVICE_HOST=http://user-service:${USER_SERVICE_PORT:-8082}
      - GATEWAY_SERVICE_HOST=http://gateway-service:${GATEWAY_SERVICE_PORT:-8088}
    networks:
      - fitness-network
    volumes:
      - ./fit-service:/app
      - maven-repo:/root/.m2
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 20s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  statistic-service:
    build:
      context: ./statistic-service
      dockerfile: Dockerfile.dev
    container_name: statistic-service
    ports:
      - "${STATISTIC_SERVICE_PORT:-8081}:8081"
    env_file:
      - .env
      - ./statistic-service/.env
    environment:
      - FIT_SERVICE_HOST=http://fit-service:${FIT_SERVICE_PORT:-8080}
      - STATISTIC_SERVICE_HOST=http://statistic-service:${STATISTIC_SERVICE_PORT:-8081}
      - USER_SERVICE_HOST=http://user-service:${USER_SERVICE_PORT:-8082}
      - GATEWAY_SERVICE_HOST=http://gateway-service:${GATEWAY_SERVICE_PORT:-8088}
    networks:
      - fitness-network
    volumes:
      - ./statistic-service:/app
      - maven-repo:/root/.m2
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 20s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile.dev
    container_name: gateway-service
    depends_on:
      - fit-service
      - statistic-service
      - user-service
    ports:
      - "8088:8088"
    env_file:
      - .env
      - ./gateway-service/.env
    environment:
      - FIT_SERVICE_HOST=http://fit-service:${FIT_SERVICE_PORT:-8080}
      - STATISTIC_SERVICE_HOST=http://statistic-service:${STATISTIC_SERVICE_PORT:-8081}
      - USER_SERVICE_HOST=http://user-service:${USER_SERVICE_PORT:-8082}
      - GATEWAY_SERVICE_HOST=http://gateway-service:${GATEWAY_SERVICE_PORT:-8088}
    networks:
      - fitness-network
    volumes:
      - ./gateway-service:/app
      - maven-repo:/root/.m2
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8088/actuator/health || exit 1" ]
      interval: 20s
      timeout: 20s
      retries: 3
    restart: always

networks:
  fitness-network:
    driver: bridge

volumes:
  maven-repo:
