version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fit-service-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_DB_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_DB_USERNAME}
      POSTGRES_DB: fitnessdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fit-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRESQL_DB_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  fit-service:
    build: .
    container_name: fit-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POSTGRESQL_DB_HOST=ep-tight-flower-a1w3np3d-pooler.ap-southeast-1.aws.neon.tech
    networks:
      - fit-network

networks:
  fit-network:
    driver: bridge

volumes:
  postgres-data:
