services:
  - type: web
    name: fit-service
    env: docker
    repo: https://github.com/FitTrack-Application/fitness.git
    branch: main
    buildCommand: mvn -B clean package --file ./pom.xml
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"