name: Deploy Statistic Service

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths: 
      - 'Team_03/02_Source/01_Source_Code/BE/services/statistic-service/**'
  pull_request:
    branches: 
      - 'main'
      - 'dev'
    paths: 
      - 'Team_03/02_Source/01_Source_Code/BE/services/statistic-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build statistic-service with Maven
      run: mvn -B clean package --file Team_03/02_Source/01_Source_Code/BE/services/statistic-service/pom.xml

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        cd Team_03/02_Source/01_Source_Code/BE/services/statistic-service
        docker build -t ${{ secrets.DOCKER_USERNAME }}/statistic-server:latest .

    - name: Push Image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/statistic-server:latest

    - name: Deploy to Render
      run: |
        curl -X POST "https://api.render.com/deploy/srv-*******?key=${{ secrets.STATISTIC_RENDER_DEPLOY_KEY }}"
    
