spring:
  application:
    name: fit-service
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_DB_HOST}:${POSTGRESQL_DB_PORT}/${POSTGRESQL_DB_NAME}?sslmode=require
    username: ${POSTGRESQL_DB_USERNAME}
    password: ${POSTGRESQL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_AUTH_SERVER_HOST}/realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${KEYCLOAK_AUTH_SERVER_HOST}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

host:
  statistic-service: ${STATISTIC_SERVICE_HOST}
  user-service: ${USER_SERVICE_HOST}
  fit-service: ${FIT_SERVICE_HOST}
  gateway-service: ${GATEWAY_SERVICE_HOST}
